### PR TITLE
Fix resize to parse heigth and width from viewBox

### LINKED ISSUE #6: omitted width/height in favor of viewbox causes resizing problems
We just received an svg from swiftly which ommitted the `width` and `height` fields:

https://github.com/logo/calq/blob/1.0.2/images/logo.svg

We're not sure whether this is a new illustrator problem, or a one-off problem with the way the designer implemented since it says generated with illustrator `17.1.0`.

@ianstormtaylor 

cc @amillet89

### PR DESCRIPTION
**Pull request by amillet89**
@ianstormtaylor @calvinfo fixes https://github.com/logo/cli/issues/6

basically parsing the width and height params from the viewBox because newer versions of AI seem to be omitting width and height from the svg tag.

### CODE REVIEW

File: lib/resize.js [hunk 1]
```diff
@@ -145,3 +146,18 @@ function shorthand(string){
 
   return ret;
 }
+
+function getDims(string){
```
Comment (ianstormtaylor) [inline lib/resize.js]: doc block for this would be good, especially since its not a very obvious function

**Comment by ianstormtaylor** [comment]
nice, looks like a good fix!

i should have made that code cleaner to begin with haha, we might have been able to use an XML parser to get rid of our regexps, but not necessary for now i guess

are we sure that it's always `viewBox`? and that we don't need to support both?

**Comment by calvinfo** [comment]
looks good to me! agree with ian that we should probably go with `width` `height` when it's available (seems like the one source of truth) and otherwise fallback to viewbox

**Comment by ianstormtaylor** [comment]
Btw, I checked a bunch of files and it seems like `viewbox` is always there, so seems we can rely on it!
